// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbnttmlsdqtznhuvmhqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtibnR0bWxzZHF0em5odXZtaHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTY0NjAsImV4cCI6MjA3MzA3MjQ2MH0.niczrK0wdClK1nJgzwFUC8V_05MTmXZ0_rGR0ENh-Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});